server:
  port: 8690
  #session-timeout: 1800
spring:
  application:
    name: PolarisSyncServer
polaris:
  sync:
    registry:
      configProvider: file
      configBackupPath: conf/registry/sync-config-backup.json
      options:
        watchFile: conf/sync-config.json
    config:
      configProvider: file
      configBackupPath: conf/config/sync-config-backup.json
      options:
        watchFile: conf/sync-config.json
logging:
  config: classpath:logback-sync.xml
  level:
    root: ${POLARIS_SYNC_LOGGER_LEVEL:info}
  path: ${POLARIS_SYNC_LOGGER_PATH:loggers}
